### ISSUE TITLE
Improve g3w suite implementation

### ISSUE THREAD

**Issue by NyakudyaA** [NyakudyaA/g3w-suite-docker#1]
# Problem

The current implementation uses QGIS Server 2.18 and we would like to use the latest QGIS Server version ie camptocamp/qgis-server:3.10 or 3liz/qgis-map-server:3.10

I tried to change the docker-compose to the following:
```
 qgisserver:
    restart: unless-stopped
    image: camptocamp/qgis-server:3.10
    #hostname: qgis-server
    container_name: qgisserver4${COMPOSE_PROJECT_NAME}
    volumes_from:
      - django
    environment:
      - QGIS_PROJECT_FILE=''
      - GIS_SERVER_LOG_LEVEL= DEBUG
      - MAX_REQUESTS_PER_PROCESS=100
    depends_on:
      db:
        condition: service_healthy
```
In django.env I changed the following
G3WSUITE_QDJANGO_SERVER_URL=http://qgisserver/ows

* When printing you see the following interface
![print](https://user-images.githubusercontent.com/2510900/73338521-75089d00-427f-11ea-89da-571b5e0dc6fa.png)

And printing a map generates the following.
![printed-map](https://user-images.githubusercontent.com/2510900/73338996-68387900-4280-11ea-903e-afc232397fb0.png)

It would be nice if we could be able to add an option for generating a map title
![print](https://user-images.githubusercontent.com/2510900/73338718-e5afb980-427f-11ea-8706-adc9b384bda0.png)

* In the Admin interface there is an option of adding base maps but I did not see how to add the URL for the base map.

The code for the g3w resides in https://github.com/g3w-suite/g3w-client
